### ISSUE TITLE
[BUG] / FeatureRequest: Unable to Continue to Change Volume while pressing button

### ISSUE THREAD

**Issue by jmcc94** [bitfocus/companion-module-spotify-remote#13]
I currently have some actions on a button like so;

![image](https://user-images.githubusercontent.com/81594959/118217553-ce72fa80-b4c9-11eb-8150-baa8a434bfdf.png)

But the volume never increases by more than 1, no matter how long I press the button down.

Other modules seem to work in this way, so I assume it's an issue with the way that Spotify handles volume. Is there a way to continually increase/decrease volume while the button is pressed down.

**Comment by bevanjkay** [comment]
@jmcc94 This is because all of the requests are sent via the Spotify Web API. When you press the button the system is asking the API for the current volume, adjusting it by the amount you specify in the "volume" input box, and then sending that to the API. When you continually send requests, it doesn't allow the requests to resolve in the appropriate order, and won't act as expected.

The only alternative I can think of is an action that allows you set the volume to a specific number value. Would that be useful for you use case?
