### ISSUE TITLE
[BUG]Spotify Connection fails (API Limit?)

### ISSUE THREAD

**Issue by AHub88** [bitfocus/companion-module-spotify-remote#30]
### Is this a bug in companion itself or a module?

- [X] I believe this to be a bug in companion

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The connection to spotify fails after 2-3 days.
The status is green and "OK", but you can no longer control spotify. 
It only works again if you create a new app in the Spotify Developer Dashboard.
I could imagine that it is due to the many requests and Spotify limits them.

![spotify](https://user-images.githubusercontent.com/99470230/153902484-df7e9038-a807-4c99-9871-ea520087eddc.jpg)

### Environment (please complete the following information)

```markdown
OS: Windows 10
Browser: Chrome 94
Companion Version: 2.2.0-b177f8fb-3722
```

**Comment by Julusian** [comment]
It appears that accounts created after May 2021 have lower api limits https://developer.spotify.com/community/news/2021/05/27/improving-the-developer-and-user-experience-for-third-party-apps/

So it is possible that you are hitting those limits.
That said, in surprised that the line really spikes up on the 9th and stays at almost double.

Also I am surprised that it breaks completely after a few days, and requires being reconfigured again. Does exiting companion for a few minutes and starting it again have the same effect?

**Comment by sytone** [comment]
I am seeing a lot of traffic as well. Hitting 350000 requests per day which... seems a lot.

**Comment by bevanjkay** [comment]
@sytone that is about right. The module is configured to poll Spotify for status every 250ms

**Comment by Julusian** [comment]
Yeah I think I have seen this happen before too. Something to do with the retries or the way the status is polled can cause it to get stuck in an almost infinite loop of polling.

This was something I was addressing in #29, by making a 'workqueue' for the polling, which ensured that there was only ever one request in flight at a time and would also limit the rate a bit. I havent finished that PR because the spotify connection library doesnt handle timeouts, so when a request times out it gets stuck waiting forever. I have been running this branch for a few weeks and observe this happening every couple of days..

**Comment by sytone** [comment]
I have pulled the module in as a volume for my docker container and updated frequency to 5000ms and it seems to be behaving better and every 5 seconds for update is more than enough for me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by joezimjs** [comment]
So is the Spotify documentation wrong? https://developer.spotify.com/documentation/web-api/guides/rate-limits/
The only rate limits it mentions are 30-second rolling limits. If it works for a couple days then stops (and then comes back about a month later in my experience), then it seems like a different limit is the problem.

In any case, it seems like adjusting that 250ms interval to something slower is an acceptable workaround for now, but it might be a good idea to listen for the 429 responses that documentation I linked to talks about. Instead of just firing on an interval, just set a timeout for the next one after each response, using the set time you come up with if it comes back as 200 but setting it long enough to clear the 429 error is one comes back.

I'd love to try to implement it myself, but I'm not sure how to edit the one installed on my Companion software nor how to install a version I've created. If I can get instructions for how to do that from someone, I might try making a PR.

**Comment by Julusian** [comment]
@joezimjs thanks, that is some good detective work there.
Yeah, I think that changing the polling time to 3s would be a good quick fix, to get the module usable for all. 
Changing the polling that slow will no doubt cause some other bug reports to appear of that the timings dont update smoothly, but that is something that can be improved later. 
I do think we should also listen to 429 responses, but that is a much larger task, and I wouldnt want to start on that until I have finally finished up #29

**Comment by joezimjs** [comment]
As for listening to 429 responses, if you look at my commit and ignore the console logs, the commented out/deleted bits that use the companion instance skeleton, and the extra run.js file, you should be able to copy that over for handling 429 responses.

**Comment by joezimjs** [comment]
Hmm... I guess I read the graphs wrong. I read it as around 35,000 but I missed a digit: they're actually saying 340,000, which means, it's including all requests, even ones that come back with a 429. I'm going to run some full days tests with the 3K ms and get back with results to see how long it lasts...

**Comment by joezimjs** [comment]
Ok, after running for over 24 hours without any rate limits hit, I think we're safe with 3 seconds. 👍

**Comment by AHub88** [comment]
Yes, I've tested it too

**Comment by Julusian** [comment]
In case 3s is not ok, this is now a config field
