### ISSUE TITLE
Trigger second windows PC with companion

### ISSUE THREAD

**Issue by ExtremGladiator** [bitfocus/companion-module-spotify-remote#39]
Hi I can't trigger a secondary Windows PC with this module. How I can get this to work.

Greedings

**Comment by Julusian** [comment]
Make sure to set the correct deviceId in the config, or use the action to update that deviceId

**Comment by ExtremGladiator** [comment]
where I can find the deviceID?

**Comment by joezimjs** [comment]
When you set up the Connection for Spotify, the instructions told you to create a button that loaded the currently playing device id into the config. If you're going to control multiple computers from one Companion installation, I believe you'll need multiple Connections for the Spotify plugin, each one configured with a separate device id. You'll likely also want to create a separate app in the Spotify developer Dashboard because doubling the number of calls to a single app's API could put it over the limit unless you don't run the computer with Companion on it for more than half a day at a time.
