### ISSUE TITLE
Floods of requests when no internet

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-spotify-remote#6]
If the `GetPlaybackState` call fails, it tries again. When there are network issues (ie no internet), this causes an unending loop. If this fails for more than 250ms, then the timer will fire again, causing it to be trying to run 2 infinite update loops in parallel. And this repeats until companion is spending all its time on getting a response.

https://github.com/bitfocus/companion-module-spotify-remote/blob/main/module.js#L268

Instead, it is probably sufficient to simply ignore a failed response. The timer will 'retry' in 250ms anyway. Alternatively, the retries should be rate limited a bit, and should block the timer firing again. The second option would be as simple as wrapping `GetPlaybackState` with [debounce-fn](https://www.npmjs.com/package/debounce-fn) set to run before, with a 100ms wait

**Comment by Simber1** [comment]
Ah I'd theorized that this was possible but never was able to actually have it happen, I think the easiest solution would be to have the errorcheck function return to indicate whether it should try again or not since this will happen with every api call, not just the GetPlaybackState, it's just more obvious with that since it's called every 250ms.

I'll take a crack at fixing this in a few days when I have some spare time.
